version: "3"
services:
  #preprocess:
   # image: gcr.io/${PROJECT_ID}/i3d-preprocess:latest
    #build:
     #   context: .
      #  dockerfile: ./preprocess/Dockerfile
    # inference:
    #     image: gcr.io/${{ secrets.PROJECT_ID}}/LSTM_inference:latest
    #     build: ./inference
    #         context: ./LSTM
    # training:
    #     image: gcr.io/${{ secrets.PROJECT_ID}}/LSTM_training:latest
    #     build: ./training
    #         context: ./LSTM
  endpoint:
    build: ./endpoint
    volumes:
      - ./endpoint:/app
      - ${GOOGLE_APPLICATION_CREDENTIALS}:/credentials/credential.json:ro
    container_name: gcp_endpoint
    command: ls /credentials #gunicorn app:app --config=/app/config.py
    ports:
      - "8080:8080"
    environment:
      # /docs/authentication/production
      GOOGLE_APPLICATION_CREDENTIALS: ${CREDENTIAL_PATH}

   