version: "3"
services:
  #preprocess:
   # image: gcr.io/${PROJECT_ID}/i3d-preprocess:latest
    #build:
     #   context: .
      #  dockerfile: ./preprocess/Dockerfile
    # inference:
    #     image: gcr.io/${{ secrets.PROJECT_ID}}/LSTM_inference:latest
    #     build: ./inference
    #         context: ./LSTM
    # training:
    #     image: gcr.io/${{ secrets.PROJECT_ID}}/LSTM_training:latest
    #     build: ./training
    #         context: ./LSTM
  endpoint:
    build: ./endpoint
    volumes:
      - ./endpoint:/app
      - ${{ secrets.SERVICE_ACCOUNT }}:/credentials/credential.json:ro
    container_name: gcp_endpoint
    command: cat /credentials/credential.json #gunicorn app:app --config=/app/config.py
    ports:
      - "8080:8080"
    
   