version: "3"
services:
    preprocess:
      image: ${REGISTRY}/${IMAGE_NAME}/preprocess:${MAIN_TAG}
      build:
          context: .
          dockerfile: ./preprocess/Dockerfile
    inference:
      image: ${REGISTRY}/${IMAGE_NAME}/inference:${MAIN_TAG}
      build:
          context: .
          dockerfile: ./inference/Dockerfile
    utils:
      image: ${REGISTRY}/${IMAGE_NAME}/utils:${MAIN_TAG}
      build:
          context: .
          dockerfile: ./utils/Dockerfile
    training:
      image: ${REGISTRY}/${IMAGE_NAME}/training:${MAIN_TAG}
      build: 
        context: .
        dockerfile: ./training/Dockerfile
        #cache_from: 
        #  - gcr.io/acbm-317517/artemisgcp_training:latest
    endpoint:
      image: ${REGISTRY}/${IMAGE_NAME}/endpoint:${MAIN_TAG}
      build:
       context: ./endpoint
       dockerfile: Dockerfile
    download_model:
      image: ${REGISTRY}/${IMAGE_NAME}/download_model:${MAIN_TAG}
      build:
        context: .
        dockerfile: ./download_model/Dockerfile
    
    # version tag the dockers
    version_preprocess:
      extends: preprocess
      image: ${REGISTRY}/${IMAGE_NAME}/preprocess:${VERSION_TAG:-dev}
    version_inference:
      extends: inference
      image: ${REGISTRY}/${IMAGE_NAME}/inference:${VERSION_TAG:-dev}
    version_utils:
      extends: utils
      image: ${REGISTRY}/${IMAGE_NAME}/utils:${VERSION_TAG:-dev}
    version_training:
      extends: training
      image: ${REGISTRY}/${IMAGE_NAME}/training:${VERSION_TAG:-dev}
    version_endpoint:
      extends: endpoint
      image: ${REGISTRY}/${IMAGE_NAME}/endpoint:${VERSION_TAG:-dev}
    version_download_model:
      extends: download_model
      image: ${REGISTRY}/${IMAGE_NAME}/download_model:${VERSION_TAG:-dev}
    

   