version: "3"
services:
    preprocess:
        image: gcr.io/${PROJECT_ID}/i3d-preprocess:latest
        build:
            context: .
            dockerfile: ./preprocess/Dockerfile
    inference:
        image: gcr.io/${PROJECT_ID}/lstm-inference:latest
        build:
            context: .
            dockerfile: ./inference/Dockerfile
    utils:
        image: gcr.io/${PROJECT_ID}/utils:latest
        build:
            context: .
            dockerfile: ./utils/Dockerfile
    # inference:
    #     image: gcr.io/${{ secrets.PROJECT_ID}}/LSTM_inference:latest
    #     build: ./inference
    #         context: ./LSTM
    # training:
    #     image: gcr.io/${{ secrets.PROJECT_ID}}/LSTM_training:latest
    #     build: ./training
    #         context: ./LSTM
    # endpoint:
    #     image: gcr.io/${{ secrets.PROJECT_ID}}/endpoint:latest
    #     build: ./endpoint
    #         context: .