version: "3"
services:
  #preprocess:
   # image: gcr.io/${PROJECT_ID}/i3d-preprocess:latest
    #build:
     #   context: .
      #  dockerfile: ./preprocess/Dockerfile
    # inference:
    #     image: gcr.io/${{ secrets.PROJECT_ID}}/LSTM_inference:latest
    #     build: ./inference
    #         context: ./LSTM
  training:
    build: 
      context: .
      dockerfile: ./training/Dockerfile
      #cache_from: 
      #  - gcr.io/acbm-317517/artemisgcp_training:latest
  endpoint:
    build: ./endpoint
    volumes:
      - ${CREDENTIAL}:/credentials/credential.json:ro
    container_name: gcp_endpoint
    command: gunicorn app:app --config=/app/config.py
    ports:
      - "8080:8080"
    
   