name: Build Image for endpoin

on: 
  push:
    branches:
      - 'main'
    tags:
      - 'v*.*.*'
  pull_request:
    branches:
      - 'main'

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: serre-lab/artemisgcp

jobs:
  build-image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to the Container registry
        uses: docker/login-action@v1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract tag name
        id: tag
        uses: actions/github-script@0.2.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            return context.payload.ref.replace(/\/refs\/tags\//, '');

      - name: Build and Push Image
        env:
          VERSION_TAG: ${{ steps.tag.outputs.tags }}
          MAIN_TAG: main
        run: |
          docker-compose up
          docker-compose push

# cd endpoint
# docker build --tag gcp-app .
# docker tag gcp-app:latest gcr.io/${{ secrets.PROJECT_ID}}/gcp-app:latest
# docker push gcr.io/${{ secrets.PROJECT_ID}}/gcp-app:latest

# docker-compose build
# docker tag artemisgcp_training:latest gcr.io/${{ secrets.PROJECT_ID}}/artemisgcp_training:latest
# docker push gcr.io/${{ secrets.PROJECT_ID}}/artemisgcp_training:latest