name: Build Image for endpoin

on: 
  push:
     

jobs:
  build-image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set Up GCloud
        uses: google-github-actions/setup-gcloud@master
        with:
          version: '290.0.1'
          project_id: ${{ secrets.PROJECT_ID }}
          service_account_key: ${{ secrets.SERVICE_ACCOUNT }}
          export_default_credentials: true
      - name: Configure Docker
        run: gcloud auth configure-docker
      - name: create JSON secret
        uses: jsdaniell/create-json@1.1.2
        with:
          name: "credentials.json"
          json: ${{ secrets.SERVICE_ACCOUNT}}
      - uses: docker/build-push-action@v2.6.1
        # Ignore the failure of a step and avoid terminating the job.
        continue-on-error: true
      - name: Build and Push Image
        run: |
          docker-compose up 
          docker image ls
          docker tag artemisgcp_training:latest gcr.io/${{ secrets.PROJECT_ID}}/artemisgcp_training:latest
          docker push gcr.io/${{ secrets.PROJECT_ID}}/artemisgcp_training:latest

          
      

# cd endpoint
# docker build --tag gcp-app .
# docker tag gcp-app:latest gcr.io/${{ secrets.PROJECT_ID}}/gcp-app:latest
# docker push gcr.io/${{ secrets.PROJECT_ID}}/gcp-app:latest