name: Build Image for endpoint

on: 
  push:
     

jobs:
  build-image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set Up GCloud
        uses: google-github-actions/setup-gcloud@master
        with:
          version: '290.0.1'
          project_id: ${{ secrets.PROJECT_ID }}
          service_account_key: ${{ secrets.SERVICE_ACCOUNT }}
          export_default_credentials: true
      - name: Configure Docker
        run: gcloud auth configure-docker
      - uses: satackey/action-docker-layer-caching@v0.0.11
        # Ignore the failure of a step and avoid terminating the job.
        continue-on-error: true
      - name: Build and Push Image
        run: |
          
          CREDENTIAL_PATH=${{ secrets.SERVICE_ACCOUNT }} docker-compose up endpoint
          docker-compose up
          ls
          
      

# cd endpoint
# docker build --tag gcp-app .
# docker tag gcp-app:latest gcr.io/${{ secrets.PROJECT_ID}}/gcp-app:latest
# docker push gcr.io/${{ secrets.PROJECT_ID}}/gcp-app:latest