name: Build Image for endpoint

on: 
  push:
    branches:
      - "*"
  pull_request:
    branches:
      - 'main'

env:
  REGISTRY: gcr.io
  IMAGE_NAME: acbm-317517

jobs:
  build-image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Set Up GCloud
        uses: google-github-actions/setup-gcloud@master
        with:
          version: '290.0.1'
          project_id: ${{ secrets.PROJECT_ID }}
          service_account_key: ${{ secrets.SERVICE_ACCOUNT }}
          export_default_credentials: true
      - name: Configure Docker
        run: gcloud auth configure-docker

      - name: Extract tag name
        id: tag
        uses: actions/github-script@0.2.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            return context.payload.ref.replace(/\/refs\/tags\//, '');

      - name: Extract branch name
        id: extract_branch
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"

      - name: Build and Push Image
        env:
          VERSION_TAG: ${{ steps.tag.outputs.tags }}
          MAIN_TAG: ${{ steps.extract_branch.outputs.branch }}
        run: |
          docker-compose build
      
      - name: Push Image
        if: ${{ steps.extract_branch.outputs.branch == 'main' && github.event_name != 'pull_request'}}
        run: |
          docker-compose push



# cd endpoint
# docker build --tag gcp-app .
# docker tag gcp-app:latest gcr.io/${{ secrets.PROJECT_ID}}/gcp-app:latest
# docker push gcr.io/${{ secrets.PROJECT_ID}}/gcp-app:latest

# docker-compose build
# docker tag artemisgcp_training:latest gcr.io/${{ secrets.PROJECT_ID}}/artemisgcp_training:latest
# docker push gcr.io/${{ secrets.PROJECT_ID}}/artemisgcp_training:latest